package model;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbggenerated Sun Jun 05 13:23:02 ICT 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_name
     *
     * @mbggenerated Sun Jun 05 13:23:02 ICT 2016
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_email
     *
     * @mbggenerated Sun Jun 05 13:23:02 ICT 2016
     */
    private String userEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbggenerated Sun Jun 05 13:23:02 ICT 2016
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.status
     *
     * @mbggenerated Sun Jun 05 13:23:02 ICT 2016
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.is_active
     *
     * @mbggenerated Sun Jun 05 13:23:02 ICT 2016
     */
    private Boolean isActive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.created_date
     *
     * @mbggenerated Sun Jun 05 13:23:02 ICT 2016
     */
    private Date createdDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.tenant_id
     *
     * @mbggenerated Sun Jun 05 13:23:02 ICT 2016
     */
    private Integer tenantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.project_role_id
     *
     * @mbggenerated Sun Jun 05 13:23:02 ICT 2016
     */
    private Integer projectRoleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.default_time_cate
     *
     * @mbggenerated Sun Jun 05 13:23:02 ICT 2016
     */
    private Integer defaultTimeCate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.activation_key
     *
     * @mbggenerated Sun Jun 05 13:23:02 ICT 2016
     */
    private String activationKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.reset_key
     *
     * @mbggenerated Sun Jun 05 13:23:02 ICT 2016
     */
    private String resetKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.reset_date
     *
     * @mbggenerated Sun Jun 05 13:23:02 ICT 2016
     */
    private Date resetDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbggenerated Sun Jun 05 13:23:02 ICT 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbggenerated Sun Jun 05 13:23:02 ICT 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_name
     *
     * @return the value of user.user_name
     *
     * @mbggenerated Sun Jun 05 13:23:02 ICT 2016
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_name
     *
     * @param userName the value for user.user_name
     *
     * @mbggenerated Sun Jun 05 13:23:02 ICT 2016
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_email
     *
     * @return the value of user.user_email
     *
     * @mbggenerated Sun Jun 05 13:23:02 ICT 2016
     */
    public String getUserEmail() {
        return userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_email
     *
     * @param userEmail the value for user.user_email
     *
     * @mbggenerated Sun Jun 05 13:23:02 ICT 2016
     */
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail == null ? null : userEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbggenerated Sun Jun 05 13:23:02 ICT 2016
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbggenerated Sun Jun 05 13:23:02 ICT 2016
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.status
     *
     * @return the value of user.status
     *
     * @mbggenerated Sun Jun 05 13:23:02 ICT 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.status
     *
     * @param status the value for user.status
     *
     * @mbggenerated Sun Jun 05 13:23:02 ICT 2016
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.is_active
     *
     * @return the value of user.is_active
     *
     * @mbggenerated Sun Jun 05 13:23:02 ICT 2016
     */
    public Boolean getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.is_active
     *
     * @param isActive the value for user.is_active
     *
     * @mbggenerated Sun Jun 05 13:23:02 ICT 2016
     */
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.created_date
     *
     * @return the value of user.created_date
     *
     * @mbggenerated Sun Jun 05 13:23:02 ICT 2016
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.created_date
     *
     * @param createdDate the value for user.created_date
     *
     * @mbggenerated Sun Jun 05 13:23:02 ICT 2016
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.tenant_id
     *
     * @return the value of user.tenant_id
     *
     * @mbggenerated Sun Jun 05 13:23:02 ICT 2016
     */
    public Integer getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.tenant_id
     *
     * @param tenantId the value for user.tenant_id
     *
     * @mbggenerated Sun Jun 05 13:23:02 ICT 2016
     */
    public void setTenantId(Integer tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.project_role_id
     *
     * @return the value of user.project_role_id
     *
     * @mbggenerated Sun Jun 05 13:23:02 ICT 2016
     */
    public Integer getProjectRoleId() {
        return projectRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.project_role_id
     *
     * @param projectRoleId the value for user.project_role_id
     *
     * @mbggenerated Sun Jun 05 13:23:02 ICT 2016
     */
    public void setProjectRoleId(Integer projectRoleId) {
        this.projectRoleId = projectRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.default_time_cate
     *
     * @return the value of user.default_time_cate
     *
     * @mbggenerated Sun Jun 05 13:23:02 ICT 2016
     */
    public Integer getDefaultTimeCate() {
        return defaultTimeCate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.default_time_cate
     *
     * @param defaultTimeCate the value for user.default_time_cate
     *
     * @mbggenerated Sun Jun 05 13:23:02 ICT 2016
     */
    public void setDefaultTimeCate(Integer defaultTimeCate) {
        this.defaultTimeCate = defaultTimeCate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.activation_key
     *
     * @return the value of user.activation_key
     *
     * @mbggenerated Sun Jun 05 13:23:02 ICT 2016
     */
    public String getActivationKey() {
        return activationKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.activation_key
     *
     * @param activationKey the value for user.activation_key
     *
     * @mbggenerated Sun Jun 05 13:23:02 ICT 2016
     */
    public void setActivationKey(String activationKey) {
        this.activationKey = activationKey == null ? null : activationKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.reset_key
     *
     * @return the value of user.reset_key
     *
     * @mbggenerated Sun Jun 05 13:23:02 ICT 2016
     */
    public String getResetKey() {
        return resetKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.reset_key
     *
     * @param resetKey the value for user.reset_key
     *
     * @mbggenerated Sun Jun 05 13:23:02 ICT 2016
     */
    public void setResetKey(String resetKey) {
        this.resetKey = resetKey == null ? null : resetKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.reset_date
     *
     * @return the value of user.reset_date
     *
     * @mbggenerated Sun Jun 05 13:23:02 ICT 2016
     */
    public Date getResetDate() {
        return resetDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.reset_date
     *
     * @param resetDate the value for user.reset_date
     *
     * @mbggenerated Sun Jun 05 13:23:02 ICT 2016
     */
    public void setResetDate(Date resetDate) {
        this.resetDate = resetDate;
    }
}