package model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbggenerated Sun Jun 05 13:23:02 ICT 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbggenerated Sun Jun 05 13:23:02 ICT 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbggenerated Sun Jun 05 13:23:02 ICT 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sun Jun 05 13:23:02 ICT 2016
     */
    public UserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sun Jun 05 13:23:02 ICT 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sun Jun 05 13:23:02 ICT 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sun Jun 05 13:23:02 ICT 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sun Jun 05 13:23:02 ICT 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sun Jun 05 13:23:02 ICT 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sun Jun 05 13:23:02 ICT 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sun Jun 05 13:23:02 ICT 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sun Jun 05 13:23:02 ICT 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sun Jun 05 13:23:02 ICT 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sun Jun 05 13:23:02 ICT 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user
     *
     * @mbggenerated Sun Jun 05 13:23:02 ICT 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUserNameIsNull() {
            addCriterion("user_name is null");
            return (Criteria) this;
        }

        public Criteria andUserNameIsNotNull() {
            addCriterion("user_name is not null");
            return (Criteria) this;
        }

        public Criteria andUserNameEqualTo(String value) {
            addCriterion("user_name =", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotEqualTo(String value) {
            addCriterion("user_name <>", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThan(String value) {
            addCriterion("user_name >", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("user_name >=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThan(String value) {
            addCriterion("user_name <", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThanOrEqualTo(String value) {
            addCriterion("user_name <=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLike(String value) {
            addCriterion("user_name like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotLike(String value) {
            addCriterion("user_name not like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameIn(List<String> values) {
            addCriterion("user_name in", values, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotIn(List<String> values) {
            addCriterion("user_name not in", values, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameBetween(String value1, String value2) {
            addCriterion("user_name between", value1, value2, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotBetween(String value1, String value2) {
            addCriterion("user_name not between", value1, value2, "userName");
            return (Criteria) this;
        }

        public Criteria andUserEmailIsNull() {
            addCriterion("user_email is null");
            return (Criteria) this;
        }

        public Criteria andUserEmailIsNotNull() {
            addCriterion("user_email is not null");
            return (Criteria) this;
        }

        public Criteria andUserEmailEqualTo(String value) {
            addCriterion("user_email =", value, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailNotEqualTo(String value) {
            addCriterion("user_email <>", value, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailGreaterThan(String value) {
            addCriterion("user_email >", value, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailGreaterThanOrEqualTo(String value) {
            addCriterion("user_email >=", value, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailLessThan(String value) {
            addCriterion("user_email <", value, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailLessThanOrEqualTo(String value) {
            addCriterion("user_email <=", value, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailLike(String value) {
            addCriterion("user_email like", value, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailNotLike(String value) {
            addCriterion("user_email not like", value, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailIn(List<String> values) {
            addCriterion("user_email in", values, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailNotIn(List<String> values) {
            addCriterion("user_email not in", values, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailBetween(String value1, String value2) {
            addCriterion("user_email between", value1, value2, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailNotBetween(String value1, String value2) {
            addCriterion("user_email not between", value1, value2, "userEmail");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNull() {
            addCriterion("password is null");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNotNull() {
            addCriterion("password is not null");
            return (Criteria) this;
        }

        public Criteria andPasswordEqualTo(String value) {
            addCriterion("password =", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotEqualTo(String value) {
            addCriterion("password <>", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThan(String value) {
            addCriterion("password >", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("password >=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThan(String value) {
            addCriterion("password <", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThanOrEqualTo(String value) {
            addCriterion("password <=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLike(String value) {
            addCriterion("password like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotLike(String value) {
            addCriterion("password not like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordIn(List<String> values) {
            addCriterion("password in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotIn(List<String> values) {
            addCriterion("password not in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordBetween(String value1, String value2) {
            addCriterion("password between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotBetween(String value1, String value2) {
            addCriterion("password not between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andIsActiveIsNull() {
            addCriterion("is_active is null");
            return (Criteria) this;
        }

        public Criteria andIsActiveIsNotNull() {
            addCriterion("is_active is not null");
            return (Criteria) this;
        }

        public Criteria andIsActiveEqualTo(Boolean value) {
            addCriterion("is_active =", value, "isActive");
            return (Criteria) this;
        }

        public Criteria andIsActiveNotEqualTo(Boolean value) {
            addCriterion("is_active <>", value, "isActive");
            return (Criteria) this;
        }

        public Criteria andIsActiveGreaterThan(Boolean value) {
            addCriterion("is_active >", value, "isActive");
            return (Criteria) this;
        }

        public Criteria andIsActiveGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_active >=", value, "isActive");
            return (Criteria) this;
        }

        public Criteria andIsActiveLessThan(Boolean value) {
            addCriterion("is_active <", value, "isActive");
            return (Criteria) this;
        }

        public Criteria andIsActiveLessThanOrEqualTo(Boolean value) {
            addCriterion("is_active <=", value, "isActive");
            return (Criteria) this;
        }

        public Criteria andIsActiveIn(List<Boolean> values) {
            addCriterion("is_active in", values, "isActive");
            return (Criteria) this;
        }

        public Criteria andIsActiveNotIn(List<Boolean> values) {
            addCriterion("is_active not in", values, "isActive");
            return (Criteria) this;
        }

        public Criteria andIsActiveBetween(Boolean value1, Boolean value2) {
            addCriterion("is_active between", value1, value2, "isActive");
            return (Criteria) this;
        }

        public Criteria andIsActiveNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_active not between", value1, value2, "isActive");
            return (Criteria) this;
        }

        public Criteria andCreatedDateIsNull() {
            addCriterion("created_date is null");
            return (Criteria) this;
        }

        public Criteria andCreatedDateIsNotNull() {
            addCriterion("created_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedDateEqualTo(Date value) {
            addCriterion("created_date =", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateNotEqualTo(Date value) {
            addCriterion("created_date <>", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateGreaterThan(Date value) {
            addCriterion("created_date >", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateGreaterThanOrEqualTo(Date value) {
            addCriterion("created_date >=", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateLessThan(Date value) {
            addCriterion("created_date <", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateLessThanOrEqualTo(Date value) {
            addCriterion("created_date <=", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateIn(List<Date> values) {
            addCriterion("created_date in", values, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateNotIn(List<Date> values) {
            addCriterion("created_date not in", values, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateBetween(Date value1, Date value2) {
            addCriterion("created_date between", value1, value2, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateNotBetween(Date value1, Date value2) {
            addCriterion("created_date not between", value1, value2, "createdDate");
            return (Criteria) this;
        }

        public Criteria andTenantIdIsNull() {
            addCriterion("tenant_id is null");
            return (Criteria) this;
        }

        public Criteria andTenantIdIsNotNull() {
            addCriterion("tenant_id is not null");
            return (Criteria) this;
        }

        public Criteria andTenantIdEqualTo(Integer value) {
            addCriterion("tenant_id =", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdNotEqualTo(Integer value) {
            addCriterion("tenant_id <>", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdGreaterThan(Integer value) {
            addCriterion("tenant_id >", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("tenant_id >=", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdLessThan(Integer value) {
            addCriterion("tenant_id <", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdLessThanOrEqualTo(Integer value) {
            addCriterion("tenant_id <=", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdIn(List<Integer> values) {
            addCriterion("tenant_id in", values, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdNotIn(List<Integer> values) {
            addCriterion("tenant_id not in", values, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdBetween(Integer value1, Integer value2) {
            addCriterion("tenant_id between", value1, value2, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdNotBetween(Integer value1, Integer value2) {
            addCriterion("tenant_id not between", value1, value2, "tenantId");
            return (Criteria) this;
        }

        public Criteria andProjectRoleIdIsNull() {
            addCriterion("project_role_id is null");
            return (Criteria) this;
        }

        public Criteria andProjectRoleIdIsNotNull() {
            addCriterion("project_role_id is not null");
            return (Criteria) this;
        }

        public Criteria andProjectRoleIdEqualTo(Integer value) {
            addCriterion("project_role_id =", value, "projectRoleId");
            return (Criteria) this;
        }

        public Criteria andProjectRoleIdNotEqualTo(Integer value) {
            addCriterion("project_role_id <>", value, "projectRoleId");
            return (Criteria) this;
        }

        public Criteria andProjectRoleIdGreaterThan(Integer value) {
            addCriterion("project_role_id >", value, "projectRoleId");
            return (Criteria) this;
        }

        public Criteria andProjectRoleIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("project_role_id >=", value, "projectRoleId");
            return (Criteria) this;
        }

        public Criteria andProjectRoleIdLessThan(Integer value) {
            addCriterion("project_role_id <", value, "projectRoleId");
            return (Criteria) this;
        }

        public Criteria andProjectRoleIdLessThanOrEqualTo(Integer value) {
            addCriterion("project_role_id <=", value, "projectRoleId");
            return (Criteria) this;
        }

        public Criteria andProjectRoleIdIn(List<Integer> values) {
            addCriterion("project_role_id in", values, "projectRoleId");
            return (Criteria) this;
        }

        public Criteria andProjectRoleIdNotIn(List<Integer> values) {
            addCriterion("project_role_id not in", values, "projectRoleId");
            return (Criteria) this;
        }

        public Criteria andProjectRoleIdBetween(Integer value1, Integer value2) {
            addCriterion("project_role_id between", value1, value2, "projectRoleId");
            return (Criteria) this;
        }

        public Criteria andProjectRoleIdNotBetween(Integer value1, Integer value2) {
            addCriterion("project_role_id not between", value1, value2, "projectRoleId");
            return (Criteria) this;
        }

        public Criteria andDefaultTimeCateIsNull() {
            addCriterion("default_time_cate is null");
            return (Criteria) this;
        }

        public Criteria andDefaultTimeCateIsNotNull() {
            addCriterion("default_time_cate is not null");
            return (Criteria) this;
        }

        public Criteria andDefaultTimeCateEqualTo(Integer value) {
            addCriterion("default_time_cate =", value, "defaultTimeCate");
            return (Criteria) this;
        }

        public Criteria andDefaultTimeCateNotEqualTo(Integer value) {
            addCriterion("default_time_cate <>", value, "defaultTimeCate");
            return (Criteria) this;
        }

        public Criteria andDefaultTimeCateGreaterThan(Integer value) {
            addCriterion("default_time_cate >", value, "defaultTimeCate");
            return (Criteria) this;
        }

        public Criteria andDefaultTimeCateGreaterThanOrEqualTo(Integer value) {
            addCriterion("default_time_cate >=", value, "defaultTimeCate");
            return (Criteria) this;
        }

        public Criteria andDefaultTimeCateLessThan(Integer value) {
            addCriterion("default_time_cate <", value, "defaultTimeCate");
            return (Criteria) this;
        }

        public Criteria andDefaultTimeCateLessThanOrEqualTo(Integer value) {
            addCriterion("default_time_cate <=", value, "defaultTimeCate");
            return (Criteria) this;
        }

        public Criteria andDefaultTimeCateIn(List<Integer> values) {
            addCriterion("default_time_cate in", values, "defaultTimeCate");
            return (Criteria) this;
        }

        public Criteria andDefaultTimeCateNotIn(List<Integer> values) {
            addCriterion("default_time_cate not in", values, "defaultTimeCate");
            return (Criteria) this;
        }

        public Criteria andDefaultTimeCateBetween(Integer value1, Integer value2) {
            addCriterion("default_time_cate between", value1, value2, "defaultTimeCate");
            return (Criteria) this;
        }

        public Criteria andDefaultTimeCateNotBetween(Integer value1, Integer value2) {
            addCriterion("default_time_cate not between", value1, value2, "defaultTimeCate");
            return (Criteria) this;
        }

        public Criteria andActivationKeyIsNull() {
            addCriterion("activation_key is null");
            return (Criteria) this;
        }

        public Criteria andActivationKeyIsNotNull() {
            addCriterion("activation_key is not null");
            return (Criteria) this;
        }

        public Criteria andActivationKeyEqualTo(String value) {
            addCriterion("activation_key =", value, "activationKey");
            return (Criteria) this;
        }

        public Criteria andActivationKeyNotEqualTo(String value) {
            addCriterion("activation_key <>", value, "activationKey");
            return (Criteria) this;
        }

        public Criteria andActivationKeyGreaterThan(String value) {
            addCriterion("activation_key >", value, "activationKey");
            return (Criteria) this;
        }

        public Criteria andActivationKeyGreaterThanOrEqualTo(String value) {
            addCriterion("activation_key >=", value, "activationKey");
            return (Criteria) this;
        }

        public Criteria andActivationKeyLessThan(String value) {
            addCriterion("activation_key <", value, "activationKey");
            return (Criteria) this;
        }

        public Criteria andActivationKeyLessThanOrEqualTo(String value) {
            addCriterion("activation_key <=", value, "activationKey");
            return (Criteria) this;
        }

        public Criteria andActivationKeyLike(String value) {
            addCriterion("activation_key like", value, "activationKey");
            return (Criteria) this;
        }

        public Criteria andActivationKeyNotLike(String value) {
            addCriterion("activation_key not like", value, "activationKey");
            return (Criteria) this;
        }

        public Criteria andActivationKeyIn(List<String> values) {
            addCriterion("activation_key in", values, "activationKey");
            return (Criteria) this;
        }

        public Criteria andActivationKeyNotIn(List<String> values) {
            addCriterion("activation_key not in", values, "activationKey");
            return (Criteria) this;
        }

        public Criteria andActivationKeyBetween(String value1, String value2) {
            addCriterion("activation_key between", value1, value2, "activationKey");
            return (Criteria) this;
        }

        public Criteria andActivationKeyNotBetween(String value1, String value2) {
            addCriterion("activation_key not between", value1, value2, "activationKey");
            return (Criteria) this;
        }

        public Criteria andResetKeyIsNull() {
            addCriterion("reset_key is null");
            return (Criteria) this;
        }

        public Criteria andResetKeyIsNotNull() {
            addCriterion("reset_key is not null");
            return (Criteria) this;
        }

        public Criteria andResetKeyEqualTo(String value) {
            addCriterion("reset_key =", value, "resetKey");
            return (Criteria) this;
        }

        public Criteria andResetKeyNotEqualTo(String value) {
            addCriterion("reset_key <>", value, "resetKey");
            return (Criteria) this;
        }

        public Criteria andResetKeyGreaterThan(String value) {
            addCriterion("reset_key >", value, "resetKey");
            return (Criteria) this;
        }

        public Criteria andResetKeyGreaterThanOrEqualTo(String value) {
            addCriterion("reset_key >=", value, "resetKey");
            return (Criteria) this;
        }

        public Criteria andResetKeyLessThan(String value) {
            addCriterion("reset_key <", value, "resetKey");
            return (Criteria) this;
        }

        public Criteria andResetKeyLessThanOrEqualTo(String value) {
            addCriterion("reset_key <=", value, "resetKey");
            return (Criteria) this;
        }

        public Criteria andResetKeyLike(String value) {
            addCriterion("reset_key like", value, "resetKey");
            return (Criteria) this;
        }

        public Criteria andResetKeyNotLike(String value) {
            addCriterion("reset_key not like", value, "resetKey");
            return (Criteria) this;
        }

        public Criteria andResetKeyIn(List<String> values) {
            addCriterion("reset_key in", values, "resetKey");
            return (Criteria) this;
        }

        public Criteria andResetKeyNotIn(List<String> values) {
            addCriterion("reset_key not in", values, "resetKey");
            return (Criteria) this;
        }

        public Criteria andResetKeyBetween(String value1, String value2) {
            addCriterion("reset_key between", value1, value2, "resetKey");
            return (Criteria) this;
        }

        public Criteria andResetKeyNotBetween(String value1, String value2) {
            addCriterion("reset_key not between", value1, value2, "resetKey");
            return (Criteria) this;
        }

        public Criteria andResetDateIsNull() {
            addCriterion("reset_date is null");
            return (Criteria) this;
        }

        public Criteria andResetDateIsNotNull() {
            addCriterion("reset_date is not null");
            return (Criteria) this;
        }

        public Criteria andResetDateEqualTo(Date value) {
            addCriterion("reset_date =", value, "resetDate");
            return (Criteria) this;
        }

        public Criteria andResetDateNotEqualTo(Date value) {
            addCriterion("reset_date <>", value, "resetDate");
            return (Criteria) this;
        }

        public Criteria andResetDateGreaterThan(Date value) {
            addCriterion("reset_date >", value, "resetDate");
            return (Criteria) this;
        }

        public Criteria andResetDateGreaterThanOrEqualTo(Date value) {
            addCriterion("reset_date >=", value, "resetDate");
            return (Criteria) this;
        }

        public Criteria andResetDateLessThan(Date value) {
            addCriterion("reset_date <", value, "resetDate");
            return (Criteria) this;
        }

        public Criteria andResetDateLessThanOrEqualTo(Date value) {
            addCriterion("reset_date <=", value, "resetDate");
            return (Criteria) this;
        }

        public Criteria andResetDateIn(List<Date> values) {
            addCriterion("reset_date in", values, "resetDate");
            return (Criteria) this;
        }

        public Criteria andResetDateNotIn(List<Date> values) {
            addCriterion("reset_date not in", values, "resetDate");
            return (Criteria) this;
        }

        public Criteria andResetDateBetween(Date value1, Date value2) {
            addCriterion("reset_date between", value1, value2, "resetDate");
            return (Criteria) this;
        }

        public Criteria andResetDateNotBetween(Date value1, Date value2) {
            addCriterion("reset_date not between", value1, value2, "resetDate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user
     *
     * @mbggenerated do_not_delete_during_merge Sun Jun 05 13:23:02 ICT 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user
     *
     * @mbggenerated Sun Jun 05 13:23:02 ICT 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}